main:
  device: cuda
  use_gpt: false
  spatial_reasoning_method: auto_region # auto_region, human_assign, none
  fast_slow_method: fast_match # slow_reasoning # fast_match
  depth_cut: 10.0
  dataset: horizon 
  scene_id: icra_ic4f # rosbag2_2025_04_08-21_33_17_new # 
  dataset_path: /mnt/holoagent/fsrvln/rgbd_datasets/
  graph_path: ${HOLOAGENT_DATA_ROOT}/VLN/instance_tracking/data/output/G1/holoagent_mapping-g1/ic_4f/graph_20260423152358
  save_path:  ${HOLOAGENT_DATA_ROOT}/VLN/instance_tracking/data/output/G1/holoagent_mapping-g1-eval
  long_query:
    spec: [obj, room, floor] # [obj, room], [obj, floor], [obj].
models:
  clip:
    type: SigLIP-384 #ViT-B-32 #ViT-H-14
    checkpoint: hf-hub:timm/ViT-SO400M-14-SigLIP-384 
