#!/usr/bin/env python3
"""Sync legacy top-level markdown files from skill READMEs."""

from __future__ import annotations

from pathlib import Path


LEGACY_MAPPING = {
    "ArmSkill.md": "arm-skill",
    "RelMoveSkill.md": "rel-move-skill",
    "RobotService.md": "robot-service",
    "SemNavSkill.md": "sem-nav-skill",
    "WorkFlow.md": "workflow",
}


def build_legacy_content(skill_name: str, readme_content: str) -> str:
    header = (
        "<!-- Auto-generated by scripts/sync_legacy_docs.py. "
        "Edit the corresponding file under skills/<skill-name>/ instead. -->\n\n"
    )
    source = f"> 来源：`skills/{skill_name}/README.md`\n\n"
    return header + source + readme_content.strip() + "\n"


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]

    for legacy_name, skill_name in LEGACY_MAPPING.items():
        readme_path = repo_root / "skills" / skill_name / "README.md"
        legacy_path = repo_root / legacy_name

        if not readme_path.exists():
            print(
                f"[WARN] README not found for skill {skill_name}: {readme_path}")
            continue

        content = readme_path.read_text(encoding="utf-8")
        legacy_path.write_text(build_legacy_content(
            skill_name, content), encoding="utf-8")
        print(f"Synced {legacy_path.name} <- skills/{skill_name}/README.md")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
